import React from "react";
import { useApp } from "../../App";

import "./Footer.scss";

export const Footer = () => {
  const { backgroundImage, path } = useApp();
  const year = new Date().getFullYear();

  return (
    <div className="footer">
      <div className="footer__bg" style={{ backgroundImage }} />
      <div className="footer__github">
        Do you want to use this website?{" "}
        <a
          href="https://github.com/interaminense/homepage"
          target="_blank"
          rel="noreferrer"
        >
          Clone my repository and enjoy it
        </a>
        !
      </div>
      <div className="footer__content">
        <div className="footer__midjourney">
          <a
            className="footer__background-page"
            href={path}
            style={{ backgroundImage }}
            target="_blank"
            rel="noreferrer"
          >
            #
          </a>
          <div className="footer__midjourney-text">
            This background image of this website was generated by midjourney
            artificial intelligence
          </div>
        </div>
        <div className="footer__signature">Adriano Interaminense © {year}</div>
      </div>
    </div>
  );
};
